name: CI (kernelridge branch)

on:
  push:
    branches: [ "kernelridge" ]

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DecisionTreeRegressor (train.py)
        run: |
          python train.py

      - name: Run KernelRidge (train2.py)
        run: |
          python train2.py
